name: Build & Test on Push
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ['pollapo', 'pb']
    defaults:
      run:
        working-directory: 'cli/${{ matrix.target }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Build
        run: deno compile -A --unstable entrypoint.ts

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Build
        run: deno test -A --unstable
