name: Build & Test on Push
on: push

jobs:
  build-pollapo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli/pollapo
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Build
        run: deno compile -A --unstable entrypoint.ts

  build-pbkit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli/pbkit
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Build
        run: deno compile -A --unstable entrypoint.ts

  test:
    runs-on: ubuntu-latest
    needs: [build-pollapo, build-pbkit]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Build
        run: deno test -A --unstable
